### ISSUE TITLE
Data save fail error alert

### ISSUE THREAD

**Issue by Marta-Russo** [lookit/ember-lookit-frameplayer#127] opened 2020-02-10 15:31 UTC
Hi, In our current project (PAIRS) we noticed an error during testing: a red box appears in the right corner of the screen saying that data can not be saved (see picture).

It happens at least one time during each testing. It goes away if you go to the next page or if you close the alert box. It has happened in different point of the study.

We are not able to test if the data are actually saved because we cannot access the server to view responses.

![Data_save_fail-2](https://user-images.githubusercontent.com/59850972/74163435-62338800-4bf0-11ea-814f-607ef15457a5.PNG)

**Comment by kimberscott** [comment] 2020-02-10 22:02
Thanks for filing a bug report about this! It's helpful to know this error doesn't recur each frame - that suggests that saving is only sometimes failing, and on the very next frame the database is actually all caught up. You can verify that once we have https://github.com/lookit/lookit-api/issues/427 closed out and you can see the responses easily to check!

For future reference, when you make a new issue, you can click the "Bug Report" type to get a template which guides you through providing some more information that will help us better understand, reproduce, & troubleshoot what's going wrong:

![Screen Shot 2020-02-10 at 4 51 39 PM](https://user-images.githubusercontent.com/9554627/74193621-a7be7800-4c25-11ea-95a6-144c90510330.png)

In this case here are some of the most relevant questions.
- Is this when previewing or participating?
- What is the link to your study?
- Which frame type or types have you seen this on?
- Does this happen at a consistent point in the study? (E.g., the 10th test trial, only one of the test trials where the game is ending and data is being saved, etc.) If it happens "randomly," any information about when you have and haven't observed it is still important, because it's very unlikely it's really random :)
- What do you see in the web console when you see this error? (See https://lookit.readthedocs.io/en/develop/tutorial-first-study.html#using-the-javascript-console-in-your-browser-to-learn-more-about-any-problems if using the web console is new!)
- What things have you tried varying (e.g., making trials shorter, changing order) and/or checked already (e.g., is your internet connection definitely working at the time you see the error)? 

My best guess, without being able to replicate this yet, is that saving is sometimes timing out when a lot of data is being sent. Separately, I strongly suspect you don't need to be storing anywhere near as much data as is being stored now; that's putting some strain on Lookit across the board (and will e.g. incur unexpected hosting costs), so I'm asking Gleb about whether this is in fact necessary. This might be a moot point if Gleb can trim things down, so up to you whether to dig in a bit deeper about when exactly this happens or wait and see if it's still a problem then. Thanks again!

**Comment by Marta-Russo** [comment] 2020-02-10 22:50
Is this when previewing or participating?
 - When participating.
What is the link to your study?
 - https://staging-lookit.cos.io/exp/studies/67/
Which frame type or types have you seen this on?
 - I don't have a statistics, but it did happen during the games and during the initial questionnaire.
Does this happen at a consistent point in the study? (E.g., the 10th test trial, only one of the test trials where the game is ending and data is being saved, etc.) If it happens "randomly," any information about when you have and haven't observed it is still important, because it's very unlikely it's really random :)
 - I can pay more attention to it and provide more details when it happens again.
What do you see in the web console when you see this error? (See https://lookit.readthedocs.io/en/develop/tutorial-first-study.html#using-the-javascript-console-in-your-browser-to-learn-more-about-any-problems if using the web console is new!)
 - Didn't know this was an option, we can let you know when it happens again and we try to access this page.
What things have you tried varying (e.g., making trials shorter, changing order) and/or checked already (e.g., is your internet connection definitely working at the time you see the error)?
- We haven't done any of this. We excluded internet connection because it happened with different computer, in different locations and with different internet connections.

I tried to reply to the best of my knowledge to these questions. If you think that the amount of data could be the problem we can try to work on that side first. But for at least 3 games we do need all the data that we are saving. Thanks!

**Comment by kimberscott** [comment] 2021-01-09 22:40
Closing this out for now as my understanding is we're not seeing this anymore, feel to reoopen as needed!

**Closed by kimberscott** 2021-01-09 22:40 UTC
Labels: Participant
